### ISSUE TITLE
我怎样去修改Resource中自定义action的response.status_code

### ISSUE THREAD

**Issue by tqq1994516** [bali-framework/bali#154]
我似乎并不能像fastapi示例那样直接在函数上加上response对象
```python
@app.put("/get-or-create-task/{task_id}", status_code=200)
def get_or_create_task(task_id: str, response: Response):
    if task_id not in tasks:
        tasks[task_id] = "This didn't exist before"
        response.status_code = status.HTTP_201_CREATED
    return tasks[task_id]
```
如果加上了response对象参数，发送接口时会提示缺少response关键字参数，这在重写ModelResource的方法时应该也会遇到；而且似乎Resource是无法使用fastapi中的Depends这个十分方便的特性，想问下是不是除了基础的crud，其他的api其实还是需要fastapi原生的方法来写,比如上传下载文件之类的，然后include_router到_app.routes里？
说到这边还有个疑问，Resource/ModelResource怎样和APIRoute配合形成类似flask和sanic中blueprint的效果？

**Comment by JoshYuJump** [comment]
在 `FastAPI` 的 docs 的高级用户指南里面有提到自定义的 `status_code`，[https://fastapi.tiangolo.com/advanced/additional-status-codes/](https://fastapi.tiangolo.com/advanced/additional-status-codes/)。Bali 的 Resource 目前并没有支持这个特性。

正如你所说，如果需要更细粒度的 `status_code`，Bali 的 Resource 是可以变成 FastAPI 的 Router 的，然后使用 FastAPI 的方式。[Override HTTP Actions](https://bali-framework.github.io/bali/resource/#override-http-actions)

```python
# Get the origin router 
router = GreeterResource.as_router()
# Override the actions using the FastAPI normal way
@router.get("/")
def root():
    return {"message": "Hello World"}
```

---

> 而且似乎Resource是无法使用fastapi中的Depends这个十分方便的特性

`Depends` 这个特性我个人还在调研，很多其他语言很早就有依赖注入，Python 的框架里面 nameko 也有类似的。

---

> Resource/ModelResource怎样和APIRoute配合形成类似flask和sanic中blueprint的效果？

Flask/Sanic 的 `Blueprint` 和 FastAPI 的 mount，看起来都是当单体项目变成复杂后需要模块的时候产生的需求。而 Bali 定位的是云原生的微服务场景，模块可能不会复杂到需要引入 `blueprint`，供你参考。

**Comment by JoshYuJump** [comment]
`Resource` 目前都使用的 FastAPI 的简单用法，从 RESTful 角度来讲，status_code 响应得并不恰当。可以当成一个需求在后续的版本处理一下。

**Comment by JoshYuJump** [comment]
> `Resource` 目前都使用的 FastAPI 的简单用法，从 RESTful 角度来讲，status_code 响应得并不恰当。可以当成一个需求在后续的版本处理一下。

PR #165
