### ISSUE TITLE
asyncio SQLAlchemy

### ISSUE THREAD

**Issue by 462548187** [bali-framework/bali#158]
ref: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html

**Comment by 462548187** [comment]
Hope to support  asyncio SQLAlchemy

**Comment by JoshYuJump** [comment]
@462548187 The feature is already supported. Here is the usage example. 
https://github.com/bali-framework/bali/blob/f70feca501b1d62a800025c67ae81bbd7fdb4cda/examples/legacy/resources/item.py#L45-L52
