### ISSUE TITLE
是否可以加个微信群或者其他沟通渠道

### ISSUE THREAD

**Issue by 462548187** [bali-framework/bali#160]

**Comment by 462548187** [comment]
我的M1 无法跑example
<img width="375" alt="image" src="https://user-images.githubusercontent.com/23581094/200994474-448b0f31-9f51-4cf6-a0ab-011c2ad84f3a.png">

**Comment by JoshYuJump** [comment]
是个好建议，你可以加一下这个群：
![bali-framework-wechat-qr](https://user-images.githubusercontent.com/5901894/201027359-f716039e-6c95-458d-b845-e3f3d2fddb5c.jpeg)

**Comment by JoshYuJump** [comment]
> 我的M1 无法跑example <img alt="image" width="375" src="https://user-images.githubusercontent.com/23581094/200994474-448b0f31-9f51-4cf6-a0ab-011c2ad84f3a.png">

Can you provide the following information?
1. Which bali version?
2. The source code of the main.py

**Comment by liusl12** [comment]
> 是个好建议，你可以加一下这个群： <img alt="male" width="300" src="https://user-images.githubusercontent.com/5901894/201027359-f716039e-6c95-458d-b845-e3f3d2fddb5c.jpeg">

过期了

**Comment by Ed-XCF** [comment]
![飞书20221124-100021](https://user-images.githubusercontent.com/63989770/203677534-78423c15-bbfa-4644-8eb1-d89015835c60.jpg)

**Comment by jiclouds** [comment]
二维码过期了，想加入学习

**Comment by JoshYuJump** [comment]
[cid:9819671B-2966-4C3E-86AA-11DA28B974DC-L0-001]

发自我的iPhone

在 2022年12月9日，16:45，jiclouds ***@***.***> 写道：

﻿

二维码过期了，想加入学习

**Comment by JoshYuJump** [comment]
@jiclouds 

<img src="https://user-images.githubusercontent.com/5901894/206738923-c0d41d83-86a8-421a-96bc-0ca3bb3b557a.jpg" width="300" alt="bali wechat group" />

**Comment by hhstore** [comment]
@JoshYuJump 

- 最近在使用 bali, 感觉还不错. 😄
- 麻烦群主, vx群, 拉一下我(id: hhglory).
- 使用中, 感觉有些参数写死了, 不方便扩展(自定义).
    - 例如: 默认 bali 的 rpc 路径是 `protos`, 不能更改, 而采用自定义 `rpc_service`, 又要手写冗余代码.
    - Bali.register(), 会同时注册 http router 和 rpc service, 无法灵活二选一. 可以加个带默认值的参数来控制.
    - `Bali()` 类是个单例, 不方便使用者进行扩展. 可以增加一个 `BaliBase()` 基类. 这样使用者, 可以基于 `BaliBase` 来扩展.
    - `Bali()` grpc 似乎还没有服务发现机制? 集成 consul/etcd 等.  
- 打算给项目贡献几个 PR, 提前沟通一下. 
- 我的 fork 分支: https://github.com/better-py/bali
- 后续会在 fork 分支上, 更新修改.

**Comment by JoshYuJump** [comment]
@hhstore 感谢你的评价，这个项目本身是为了解决我们团队内部转微服务之后开发效率的问题。微信群我发出来了，人不多，你可以加一下。
![20CBFBC4-C92E-4493-B683-32B6E2A80430](https://user-images.githubusercontent.com/5901894/222942351-e2a5452c-794f-4684-b053-5dd3882b69e1.jpeg)

**Comment by yogerhub** [comment]
能再发一遍群二维码吗

**Comment by JoshYuJump** [comment]
![CE4FDC68-F110-4263-88FF-28260907F41B](https://user-images.githubusercontent.com/5901894/233819179-da10fa8c-45b1-4a84-81f3-02f25817b78b.jpeg)

**Comment by zhimingzhang123** [comment]
二维码过期了。想问一下如何在bali中添加middleware，如jwt鉴权。

**Comment by Ed-XCF** [comment]
> 

![img_v2_269fdc9a-5ee9-4c11-8ec6-a167785fce2g](https://github.com/bali-framework/bali/assets/63989770/208adf63-70ef-427e-92c4-30c6be9b94f7)

**Comment by Ed-XCF** [comment]
@zhimingzhang123

**Comment by JoshYuJump** [comment]
> 二维码过期了。想问一下如何在bali中添加middleware，如jwt鉴权。

Bali 本身是对 FastAPI 的简单封装，支持 FastAPI 的 Middleware，添加也类似。

**Comment by rudy-tao** [comment]
过期了

> > 
> 
> ![img_v2_269fdc9a-5ee9-4c11-8ec6-a167785fce2g](https://private-user-images.githubusercontent.com/63989770/246332359-208adf63-70ef-427e-92c4-30c6be9b94f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDI1MjMsIm5iZiI6MTcwMzE0MjIyMywicGF0aCI6Ii82Mzk4OTc3MC8yNDYzMzIzNTktMjA4YWRmNjMtNzBlZi00MjdlLTkyYzQtMzBjNmJlOWI5NGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OTQ0ZGYyODVjNjMwZjY1ODM5YWQ3MTQyM2JjY2M5MThhZTFlODA1ZDg4ZjFhOTVjZGI4YTY5MmZmNTVlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dE6tXAi3VKiK0QYb-UDE0MBksp8j1WZ-k-UCNljiaiM)

**Comment by rudy-tao** [comment]
过期了

**Comment by JoshYuJump** [comment]
@rudy-tao 加你微信了
